#!/bin/bash
#touch 16-whatsnext 17-hidethisword 18-lettersonly 19-AZ 20-hiago 21-reverse 22-users_and_homes
#echo "#!/bin/bash">> 17-hidethisword
echo "
#echo "#!/bin/bash" >> 18-lettersonly
#echo "#!/bin/bash" >> 19-AZ
#echo "#!/bin/bash" >> 20-hiago
#echo "#!/bin/bash" >> 21-reverse
#echo "#!/bin/bash" >> 22-users_and_homes
#chmod u+x 17-hidethisword 22-users_and_homes 21-reverse 20-hiago 19-AZ 18-lettersonly 16-whatsnext
