#!/bin/bash
touch 7-everybody 8-James_Bond 9_John_Doe 10_mirror_permissions 11-directories_permissions 12-directory_permissions 13-change_group
echo "#!/bin/bash" | tee -a 7-everybody 8-James_Bond 13-change_group
chmod u+x 7-everybody 8-James_Bond 9_John_Doe 10_mirror_permissions 11-directories_permissions 12-directory_permissions 13-change_group


